sudo: required
dist: xenial
language: go
go:
  - 1.10.4
before_install:
  - sudo apt-get update -yq
script:
  - make docker-test
notifications:
  email:
    recipients:
      - aditya@portworx.com
      - eng@portworx.com
    on_success: change
    on_failure: always
after_success:
- bash <(curl -s https://codecov.io/bash)